W10D1/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: [:index, :new]
  end
  resources :albums, only: [:create, :update, :show, :destroy, :edit]
end

W10D1/music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :title, uniqueness: true

  belongs_to :band,
    class_name: :Band,
    primary_key: :id,
    foreign_key: :band_id
end

W10D1/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    class_name: :Album,
    primary_key: :id,
    foreign_key: :band_id
end

W10D1/music_app/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 8 }, allow_nil: true

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.is_password?(password) ? user :nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

W10D1/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index

  end

  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def show
    render :show
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      flash[:success] = "successfully created album!"
      redirect_to bands_url(@album.band_id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  private
  def album_params
    params.require(:album).permit(:band_id, :title, :year, :live)
  end
end

W10D1/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def logged_in?
    !!current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
end

W10D1/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new, status: 422
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W10D1/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      log_in_user!(user)
      redirect_to user_url(user.id)
    else
      flash.now[:errors] = "Wrong email/password combination"
      render :new
    end
  end

  def destroy

  end
end

W10D1/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to bands_url
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W10D1/music_app/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    <<-HTML.html_safe
      <input 
      type="hidden" 
      name="authenticity_token" 
      value="#{ form_authenticity_token }" />
    HTML
  end

end

W10D1/music_app/app/views/albums/new.html.erb
<h3>Create a new album!</h3>

<form action="<%= albums_url %>" method="post">
  <%= auth_token %>

  <label for="title">Title</label>
  <input type="text" id="title", name="album[title]" >

  <label for="year">Year</label>
  <input type="text" id="year", name="album[year]" >

  <label for="band">Band</label>
  <select name="album[band_id]" id="band">
    <option selected>==Please Select the band==</option>
    <% @bands.each do |band| %>
      <option value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
    
  </select>

  <button>Create</button>
</form>

W10D1/music_app/app/views/albums/show.html.erb
<h3><%= @album.name %></h3>

<a href="<%= edit_album_url(@album.id) %>">Edit this album</a>

<br>

<a href="<%= new_band_album_url %>">Make a new album</a>

<a href="<%= bands_url %>">Index</a>

W10D1/music_app/app/views/bands/_form.html.erb
<% action = (band.persisted? ? band_url(band.id) : bands_url) %>
<% method = (band.persisted? ? "put" : "post") %>
<% button = (band.persisted? ? "Edit" : "Create") %>

<form action="<%= action %>" method="POST">
<input type="hidden" name="_method" value="<%= method %>">
<%= auth_token %>

  <label for="bandname">What is your band's name?</label>
  <input type="string"
        id="bandname" 
        name="band[name]" value="<%= band.name %>" />

  <input type="submit" value="<%= button %>">
</form>

W10D1/music_app/app/views/bands/edit.html.erb
<h3>Edit the band!</h3>

<%= render "form", band: @band %>

<br>
<br>
<form action="<%= band_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="delete">

  <input type="submit" value="Delete this band">


  <br>
  <a href="<%= bands_url %>">Back to index</a>
</form>

W10D1/music_app/app/views/bands/index.html.erb
<h2>All the bands</h2>

<% auth_token %>

<% @bands.each do |band| %>
  <ul>
    <li><a href="<%= band_url(band.id) %>"><%= band.name %></a></li>
  </ul>
<% end %>

<h3><a href="<%= new_band_url %>">Form a new band!</a></h3>

W10D1/music_app/app/views/bands/new.html.erb
<h2>Enter a new band</h2>

<%= render "form", band: @band %>

W10D1/music_app/app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<% @band.albums.each do |album| %>
  <ul>
    <li>
      <a href="<%= album_url(album.id) %>"><%= album.title %></a>
    </li>
  </ul>
<% end %>

<a href="<%= edit_band_url(@band.id) %>">Edit this band</a>

<br>

<a href="<%= new_band_album_url(@band.id) %>">Make a new album</a>

<a href="<%= bands_url %>">Index</a>

W10D1/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header><h1>Music App</h1></header>

  <body>
    
    
    <% if !current_user.nil? %>
    <h3 class="flex">Welcome back, <%= current_user.name %></h3>
    <% else %>
    <a href="<%= new_session_url %>">Sign In</a>
    <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    
    <br>

    <%= flash[:errors] %>
    <%= yield %>
  </body>
</html>

W10D1/music_app/app/views/users/new.html.erb
<h3>Sign Up!</h3>

<form action="<%= users_url %>" method="post">
  <input 
    type="hidden" 
    name="authenticity_token" 
    value="<%= form_authenticity_token %>" />

  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <button>Create User</button>

</form>